name: resepmakanan
description: "Aplikasi Resep Tradisional"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chef.jpg
    - assets/images/gado_gado.jpg
    - assets/images/logo.png
    - assets/images/nasi_uduk.jpg
    - assets/images/rendang.jpg
    - assets/images/sate_ayam.jpg
    - assets/images/soto_betawi.jpg